version: '3.4'
services:
  db:
    image: registry.redhat.io/rhel9/postgresql-15
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_USER: graviton
      POSTGRESQL_PASSWORD: graviton
      POSTGRESQL_DATABASE: graviton
      #POSTGRES_HOST_AUTH_METHOD: trust
    #volumes:
      #- ./db:/postgresql-start:ro,z
    #healthcheck:
      #test: ["CMD", "pg_isready", "-d", "graviton"]
      #timeout: 5s
      #retries: 3

